plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.msag1reader'
    compileSdk 35
    defaultConfig {
        applicationId 'com.example.msag1reader'
        minSdk 19
        targetSdk 35
        versionCode 2
        versionName '1.1'
    }
    buildTypes {
        release { minifyEnabled false }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    applicationVariants.all { variant ->
        variant.outputs.all { outputFileName = "MSA-G1-Scanner-v${defaultConfig.versionName}.apk" }
    }
}
